### ISSUE TITLE
Swarm Support

### ISSUE THREAD

**Issue by voodootikigod** [voodootikigod/node-rolling-spider#31]
Currently this is designed for 1:1 process to drone mapping. I want SWARMS!!!!

**Comment by voodootikigod** [comment]
https://github.com/FluffyJack/node-rolling-spider/tree/swarm

Readme coming soon but short is in

https://github.com/FluffyJack/node-rolling-spider/blob/swarm/eg/swarm.js

**Comment by Resseguie** [comment]
Fixed in #47? Believe you can close this @voodootikigod

**Comment by voodootikigod** [comment]
correct!
