### ISSUE TITLE
New Parrot Airborne compatibility

### ISSUE THREAD

**Issue by jtbonhomme** [voodootikigod/node-rolling-spider#66]
Hi,

Do you think this lib could work with the new Parrot's Airborne drones ?

Best regards,
Jean-Thierry

**Comment by AlbertoHdezCerezo** [comment]
Hi jtbonhomme,

Days ago I had the same doubt, but consulting on the internet I saw that the Airborne is a modification of the Spider, so, the answer should be yes (they are the same device with different design).

**Comment by jtbonhomme** [comment]
Hi,

Thank you for your message. I bougth an Airborne minidrone and tested with a recent mac book pro laptop (with BLE) and it's Ok !

Regards,
Jean-Thierry

**Comment by jtbonhomme** [comment]
Thanks for your message, I had the same feedback from a Parrot's tech
leader, he kindly answered to me. I did not realize that my macbook was too
old and did not have BLE :)

2015-11-22 22:05 GMT+01:00 AlbertoHdezCerezo notifications@github.com:
