### ISSUE TITLE
Night Drone Supprt

### ISSUE THREAD

**Issue by gamewagon** [voodootikigod/node-rolling-spider#80]
Just had a new issues that I could not find specifically referenced and thought I'd let you know. The new night drones seem to have a new name prefix (Swat_) so to make them discoverable I added the following:

`localName.indexOf('Swat_')=== 0)` to the drone.js

Hope this helps someone else.

J

**Comment by artob** [comment]
@gamewagon Thanks for that, indeed it did help me.

**Comment by mikkab** [comment]
Blaze_ prefix for Airborne Night Blaze
