### ISSUE TITLE
"You must have bluetooth enabled and be connected to a drone" error

### ISSUE THREAD

**Issue by remzinho** [voodootikigod/node-rolling-spider#84]
Not sure if this repo is active but giving this a try:
I'm running this in Ubuntu 16.04 64.
Installed all pre-reqs.
connected ubuntu to the Maclane drone
then ran the `discover.js` with sudo in a terminal
got `noble: unknown peripheral <addr> connected` 
immediately after got `noble: unknown peripheral <addr> disconnected`
then i ran `sudo node reconnect.js` in a different terminal (`reconnect.js` is a bit modified to just do the take off and landing)

i get the following error:
```
Prepare for take off!  Maclan_033049
/home/remzi/Desktop/workspace/node-rolling-spider/lib/drone.js:342
      throw e;
      ^

Error: You must have bluetooth enabled and be connected to a drone before executing a command. Please ensure Bluetooth is enabled on your machine and you are connected.
    at Drone.writeTo (/home/remzi/Desktop/workspace/node-rolling-spider/lib/drone.js:338:13)
    at Drone.flatTrim (/home/remzi/Desktop/workspace/node-rolling-spider/lib/drone.js:631:8)
    at /home/remzi/Desktop/workspace/node-rolling-spider/eg/reconnect.js:17:9
    at Drone.<anonymous> (/home/remzi/Desktop/workspace/node-rolling-spider/lib/drone.js:144:11)
    at Peripheral.<anonymous> (/home/remzi/Desktop/workspace/node-rolling-spider/node_modules/noble/lib/peripheral.js:38:7)
    at Peripheral.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Peripheral.emit (events.js:188:7)
    at Noble.onConnect (/home/remzi/Desktop/workspace/node-rolling-spider/node_modules/noble/lib/noble.js:151:16)
    at emitTwo (events.js:106:13)
```

Am i missing something?

**Comment by lynnaloo** [comment]
@remzi-e is this still an issue?

**Comment by remzinho** [comment]
i still get the `unknown peripheral <addr> connected` error when running the discover.js example
don't get the error though.
should we close this and open a different issue?

**Comment by lynnaloo** [comment]
Which Parrot drone is this? That `unknown` error is likely because the `Maclan_` prefix isn't in the list of drones that are supported. I can add that and try to provide a more information in the case of unknown drones.

**Comment by remzinho** [comment]
i get this with both Airborne Night Maclane and the Mambo models.

**Comment by remzinho** [comment]
should this issue be renamed?

**Comment by lynnaloo** [comment]
Did you already run this:

`sudo apt-get install bluetooth bluez libbluetooth-dev libudev-dev`

**Comment by remzinho** [comment]
of course. i can get the drones moving (1 by 1) using the `index.js` script but the `discover.js` script throws that `unknown` output everytime i run it after connecting to the drone from the OS.

**Comment by lynnaloo** [comment]
Are you pairing the drone with Bluetooth through Ubuntu before running `discover.js`? If that's the case, then you only want to do it through this application since `noble` does the pairing.

**Comment by remzinho** [comment]
yeah, i thought that was the normal workflow.
if i don't do that before, there is not output from `discover.js`.
`index.js` is successful in connecting and doing what it does, though.

**Comment by lynnaloo** [comment]
Can you console.log `peripheral` here: https://github.com/voodootikigod/node-rolling-spider/blob/master/eg/discover.js#L17? I suspect it's not making it past that conditional check. 

Also, make sure you're using version `1.7.0`. We just published that today.

**Comment by lynnaloo** [comment]
@remzi-e can we close this one?

**Comment by remzinho** [comment]
Yes.
