### ISSUE TITLE
support for Parrot Mambo?

### ISSUE THREAD

**Issue by remzinho** [voodootikigod/node-rolling-spider#85]
Discover.js does not see the Parrot Mambo minidrones. Are there any modifications i can do to make Mambo discoverable?

**Comment by m6sec** [comment]
You can modify the following line in drone.js (I think it's ~94):
```
    && (localName.indexOf('RS_') === 0 || localName.indexOf('Mars_') === 0 || localName.indexOf('Travis_') === 0  || localName.indexOf('Maclan_')=== 0 || localName.indexOf('Mambo_')===0);
```

**Comment by lynnaloo** [comment]
This should be working in 1.6.0.

**Comment by edwanvi** [comment]
Yay, necroposting!

Should this be added to the readme so that people know that this library works with other, non-spider drones (ie. the Mambo)?
