### ISSUE TITLE
Drone status

### ISSUE THREAD

**Issue by dkhan11** [voodootikigod/node-rolling-spider#90]
Hi,

I'm using the latest version on a Swat drone.
The main problem is that connecting to a drone which is already flying is working well, but always shows flying is 'false'. Example:
{"status": {"flying": false, "stateValue": 0, "battery": 32}

Since the drone is in the air, this is wrong...

Thanks,
DD.

**Comment by lynnaloo** [comment]
This is related to some of the comments in #60. We're looking into the issues with the flying status.

**Comment by dkhan11** [comment]
Ok, thank you for the update!
